version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/bundle_cache
    ports:
      - 3000:3000
    environment:
      BUNDLE_PATH: /bundle_cache
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres

  db:
    image: postgres:10

  bundle_cache:
    image: busybox
    volumes:
      - /bundle_cache

volumes:
  bundle_cache:
